### ISSUE TITLE
profile template view

### ISSUE THREAD

**Issue by aldraco** [FCCWebCrafts/timeCoordinatorApp#11]
This would be the dashboard we talked about - shows all the Meetings and User information.

**Comment by germainep** [comment]
This is almost ready to close

**Comment by aldraco** [comment]
@germainep can I assign you, so people know you're already working on this?

**Comment by germainep** [comment]
The latest pull request to the angular branch will complete this except for updating the meeting

**Comment by germainep** [comment]
I would like some feedback on the execution of the meeting view how it currently works and suggestion on how it could be better

**Comment by aldraco** [comment]
I like that it's all one page. Would the sidebar be present when adding availability to meetings? We just might need more room for that task, don't know.

**Comment by aldraco** [comment]
Or perhaps making that sidebar smaller, or collapsible. Most of the stuff on there is admin panel-type stuff, so some users might just want to configure it once and be done.

**Comment by aldraco** [comment]
If anyone else has feedback, please leave it here, otherwise I'm going to close this soon just to clear out our errors/issues page a little bit. Thanks.
