### ISSUE TITLE
PUT to update username does not work with forms

### ISSUE THREAD

**Issue by aldraco** [FCCWebCrafts/timeCoordinatorApp#25]
need: a way for the user to specify or change their username.

Right now this operation works when using POSTman client, but does not work when using a web form. The parameters are put in the query string, not in the body.

**Comment by germainep** [comment]
I believe this is a result of username being associated with passport. It can be updated correctly if you change to identifier to name in the model.

**Comment by germainep** [comment]
is this issue closed yet

**Comment by aldraco** [comment]
no. have you found a way to fix it?

**Comment by aldraco** [comment]
The form right now is making a GET request to users/userid instead of making a PUT. it never touches the user controller.
