### ISSUE TITLE
better error status codes

### ISSUE THREAD

**Issue by aldraco** [FCCWebCrafts/timeCoordinatorApp#31]
The http status codes are fairly specific and it would be great if our error reporting was accurate. 

For example: 
400 is "bad request"
404 is "not found"
403 is "forbidden"

etc.

Link: http://www.iana.org/assignments/http-status-codes/http-status-codes.xhtml

This is sort of an ongoing thing as we keep adding stuff.

**Comment by ghost** [comment]
Would these be status codes for api errors? Entire site?

For apis though, right now if you visit /apit/meetings while not logged in, your redirected to the login page. I'm not sure what the other endpoints return.

Should api requests return JSON on failures like that? Like a 404 with a JSON message saying you need to be logged in.

**Comment by aldraco** [comment]
Primarily for the API error handling. I believe failures just return status codes, i.e. res.sendStatus(400); or something like that. I don't know if they send JSON messages too but it would be worth looking into.

@germainep is working on adding the Angular bits at the moment, so whatever the API spits out for failures needs to play nice with how he's going to have things set up. I would coordinate with him before changing anything.

the isLoggedIn redirect you mentioned is probably going to change as well as a result of adding Angular, since redirects will happen on the front; it's not permanent, so for now, let's leave it alone.

**Comment by aldraco** [comment]
Actually, 401 is "access denied," so perhaps that function could return a 401 error.

**Comment by aldraco** [comment]
The islogged in function still returns a redirect. @germainep how is the angular using the authentication/login functions right now? They need to be structured to just return status codes or information, not redirects for URLs, to be REST compliant, so if the front is using redirects we should probably talk about changing it.

**Comment by germainep** [comment]
actually I haven't made any attempts to fix it yet but you are correct. I haven't implemented the authentication on the angular side yet. Basically is only authenticates on the back-end when request are made for the time being which causes a bug that makes the session timeout weather its idle or not. When you log back in it takes you to the json that's being requested instead of back to the page you were on.

**Comment by germainep** [comment]
Issue completed in PR #78

**Comment by aldraco** [comment]
I'll close this for now, and we can revisit later if we need to. Thanks @jameskopacz for your help with this earlier.
