### ISSUE TITLE
the admin and participants names won't populate in the user module

### ISSUE THREAD

**Issue by germainep** [FCCWebCrafts/timeCoordinatorApp#40]

**Comment by aldraco** [comment]
I think I see it now. I can fix that tomorrow. What all do you need populated? i.e. which parts of each meeting? It can return the whole thing, or just the meeting_id, name, etc. if you want.

**Comment by germainep** [comment]
it's on the path I'm using for the user views I can populate the meetings from the user data but that data won't populate the admin and user names. simply there is no second level population I'm working on it but I'd like some help if possible

**Comment by aldraco** [comment]
You could also make a call to /api/meetings for that information. Right now that just returns all meetings, but there is a TODO to get it to filter only for meetings the user is a part of, so once that's accomplished, that would get you the info you need and would maintain a separation between user/meeting data.

**Comment by germainep** [comment]
is anyone working on that todo.

**Comment by aldraco** [comment]
not that i heard of. i had planned to, but i can't today.

**Comment by ghost** [comment]
Does #50 help?

Specifically:

> Right now that just returns all meetings, but there is a TODO to get it to filter only for meetings the user is a part of

**Comment by aldraco** [comment]
Closing as this is addressed in PR #50 and with a different strategy.
