### ISSUE TITLE
[Question] Is there a reason for having /auth/auth/[provider]?

### ISSUE THREAD

**Issue by ghost** [FCCWebCrafts/timeCoordinatorApp#54]
Why /auth/auth/twitter|facebook|google instead of /auth/twitter|facebook|google?

**Comment by aldraco** [comment]
Yes - previously all of the authentication routes were behind an /auth path, and I had prefixed them again with /auth. germaine talked me down from that ledge.

Those would have been changed by now. Where you are finding these routes?

**Comment by ghost** [comment]
In [config/secrets.js](https://github.com/FCCWebCrafts/timeCoordinatorApp/blob/development/config/secrets.js#L15-L26), [views/login.jade](https://github.com/FCCWebCrafts/timeCoordinatorApp/blob/development/views/login.jade#L17), and [views/signup.jade](https://github.com/FCCWebCrafts/timeCoordinatorApp/blob/development/views/signup.jade#L15)

**Comment by germainep** [comment]
this is fixed in the soon to be merged angular branch
