### ISSUE TITLE
Possible controllers/users.js error

### ISSUE THREAD

**Issue by ghost** [FCCWebCrafts/timeCoordinatorApp#56]
In `exports.read` if an error occurs there are 2 outputs. The 404 from the [if (err)](https://github.com/FCCWebCrafts/timeCoordinatorApp/blob/development/controllers/users.js#L15) and then a 404 from [!user](https://github.com/FCCWebCrafts/timeCoordinatorApp/blob/development/controllers/users.js#L18).

This causes `Error: Can't set headers after they are sent.` This only happens if you use an id that isn't a valid ObjectId (eg: `/api/users/55171b1c16e8d69402f581e0` is OK. `/api/users/1` causes `err` to trigger). But I think if there was a database error (like a connection problem) then you would get this same Can't set headers error.

The simplest fix looks like having the `err` 404 be a return: `return res.send(404);` so that the second 404 doesn't trigger. A problem with this is if there's a database error then the front-end won't know, It'll just be told 404 and would think that the user doesn't exist when it actually might.

I'm not sure exactly what endpoints should be returning so I've only thought of quick solutions that return what's already there. But if I were to refactor it, I think I'd have it look like this:

``` javascript
exports.read = function(req, res) {
    // check if user_id is a valid objectId
    if (mongoose.Types.ObjectId.isValid(req.params.user_id) === false) {
        // if invalid, quit with same error as user not existing.
        return res.status(404).send("This user does not exist.");
    }
    User.findById(req.params.user_id, function(err, user) {
        // now err won't fire from invalid ObjectIds
        if (err) {
            // return 500 reror instead of 404 since this should only
            // happen if error is database related not on bad input.
            return res.status(500).send(err.message);
        }
        // keep everything else the same
        if (!user) {
            res.status(404).send("This user does not exist.");
        } else {
            var o = {
                name: user.name,
                meetings: user.meetings
            };
            res.json(o);
        }
    });
};
```

**Comment by aldraco** [comment]
Weird, I could have sworn I already commented on this ...

I think the return res.status is a good call. 

I think perhaps an invalid userID should be a different error code than user not found? e.g. 400 is bad request.

**Comment by ghost** [comment]
Yeah, that makes more sense.

**Comment by aldraco** [comment]
@jameskopacz did you submit a PR for this? I think your addition was a good one.

**Comment by ghost** [comment]
I haven't yet but will later today.

**Comment by ghost** [comment]
#64
