### ISSUE TITLE
jade linting/formatting error

### ISSUE THREAD

**Issue by aldraco** [FCCWebCrafts/timeCoordinatorApp#63]
![screen shot 2015-04-06 at 2 21 02 pm](https://cloud.githubusercontent.com/assets/9719214/7009442/44731580-dc68-11e4-9180-9c3d98572e00.png)

Not sure what's going on here. Any ideas?

**Comment by germainep** [comment]
I'll do a pull request to have this fixed along with some front-end formatting today.
