### ISSUE TITLE
Test for milestone issue tracking: upcoming meetings

### ISSUE THREAD

**Issue by aldraco** [FCCWebCrafts/timeCoordinatorApp#66]
When I click 'upcoming meetings' on the login page nothing happens.

The main profile/meetings page already shows upcoming meetings, so perhaps this needs to be worded differently or taken out.

**Comment by germainep** [comment]
There is no upcoming meeting link on the login page

**Comment by aldraco** [comment]
Sorry, I miscommunicated. 

Not the login page itself, but the page that you visit first after logging in - basically the profile page. IT's above the list of meetings on the right panel.

**Comment by germainep** [comment]
That link is to get you back from the single meeting view. It was created before the single meeting view was complete, I can implement it as a back button on the single meeting view

**Comment by aldraco** [comment]
gotcha - thanks.
