### ISSUE TITLE
Meetings can be created in the past

### ISSUE THREAD

**Issue by aldraco** [FCCWebCrafts/timeCoordinatorApp#67]
The min date on the date picker should probably be set to Today or something like that.

**Comment by germainep** [comment]
I'm aware of this issue and I'm planning out a solution that alerts that the date is in the past. I'm wondering if we should clean meetings from the database that are in the past as well

**Comment by aldraco** [comment]
I think the javascript alerts could easily be replaced by modals or an angular error message (ng-valid/invalid etc).

You can also usually set a 'mindate' option on datepicker directives that limit the user from picking dates in the past. Just initalize it in the controller as mindate = new Date() and it will set it as the current date.

**Comment by germainep** [comment]
ok

**Comment by aldraco** [comment]
I can get working on this, as well as cleaning out old meetings (which I agree should definitely be done!)

**Comment by germainep** [comment]
ok that's great we also need to be able to remove the meeting reference id from the user collection when the meeting is deleted. I figure this is in the same realm as this issue.

**Comment by germainep** [comment]
this will be fixed in PR #82 by adding the angular datepick we are able to set the min-date to todays date
