### ISSUE TITLE
Services show as unconnected when they were used to log in.

### ISSUE THREAD

**Issue by aldraco** [FCCWebCrafts/timeCoordinatorApp#68]
I know the idea was so that users could reconnect if they wanted to, but I have a few concerns about this:
1) Users may not be happy to learn that the data they said they wanted to disconnect is still being stored in our database.

2) If a user tries to log back in with Twitter (a clean new login, not logging in via some other method and connecting) and sees their own data but no Twitter connection, they may be confused.

My preference would be to first:
- completely delete that data when they click reconnect, allowing them to connect it again later provided they log in via another service.
- make sure that they have at least one way to log in at all times - if they are about to delete their only login method, they should be warned.

The main concern here is that users have complete control over their own information. We want to make sure they are aware of what we are keeping and why, and have the ability to delete it if they so choose. We want to do right by our lovely users :)

**Comment by germainep** [comment]
I was able to get this fixed in PR #82  the social connections are deleted when unlinked.
