### ISSUE TITLE
TODO: Adding Availability

### ISSUE THREAD

**Issue by aldraco** [FCCWebCrafts/timeCoordinatorApp#69]
There is an availability object model. It is structured as a sub document and has a start Date and end Date.

Dates should be saved as UTC since this is how the app will be able to compare times across time zones.

This would probably require making:
- view for adding availability
- controllers for processing the data
- view for showing availability (heat map?)
- way to edit your availability
- way to delete availability

Anything else??

**Comment by germainep** [comment]
as of now the plan is to have the availability added on the single meeting view. I have built-out the controllers but I need to know should it be save to its own document in the database.

**Comment by aldraco** [comment]
they are sub documents - so they are completely contained within the meeting, not separated. availability on its own does not make sense as a singleton object. 

The add availability controller basically updates the meeting object by adding the availabilty sub document into the availability array within the meeting itself.

**Comment by germainep** [comment]
Ok that is how it is now.

**Comment by aldraco** [comment]
awesome.

**Comment by germainep** [comment]
I'm having trouble getting the the date to be set to the date of the meeting for availability. I also I think It maybe simpler to change availability from with-in the meeting object. I'm having issues with it not updating changes correctly because we are getting it from the meeting route but setting it on the availability route. I think the only way to have this issue fixed it to handle availability from within the meeting or to make availability its own document in the database. I also have an issue trying to populate the name.

**Comment by johnstonbl01** [comment]
Hi guys - I've got a question (and I'm new to the project, so I apologize if I'm asking something that's already been discussed):

Why wouldn't the availability objects also be sub-documents within the user object? If the primary goal is to match availability between users, then I think that would make it easier to compare availability across users. Additionally, I think that within the meeting objects, we could query the user admin object to get availability, and then perform the algorithm that matches availability between the administrator and the participants.

Also - for availability: what is the plan for an admin if they are trying to schedule a meeting, but the participants haven't submitted availability? I'm thinking if this is the case, we would want to add a feature for the admin / organizer to e-mail the proposed participants?

**Comment by germainep** [comment]
Well the user is referenced in the availability and we would like to keep the meetings modular. The way it works now is linear you have a user who belongs to meetings and those members availability as that meeting is concerned. If you have availability in the user model then you have to link that to each meeting. Which would cause you to search each meeting for admin and participants. 

Once the meeting is set up the admin will be able to send an email invite to add users to the meeting. We are also planning a Rolodex feature that allows users that are already members of the app to be queried and sent an in app notification as well

**Comment by johnstonbl01** [comment]
Ok - so I think I may be misunderstanding the goal of the app. The goal of the app is to see availability for a specific meeting? And as a user I need to specify my availability on a per meeting basis?

I was thinking that availability should supersede meetings, but it sounds like the we want people to set availability on a per-meeting basis. Right? Would participants have to specify specific availability for each meeting? What if they have multiple people trying to schedule meetings with them (not sure how common this would be, so just asking)?

Just trying to wrap my head around the vision...

**Comment by germainep** [comment]
You are right it is on a per meeting basis. We are aiming at some sort of calendar intergration in the long game. So your meetings can be added to google calendar, iCal ect. My view is just about everyone has access to a calendar app so let's make life easier and intergrate with what a person all ready uses.

**Comment by johnstonbl01** [comment]
Ok - I'm with you now; thanks for clarifying. Did you still want help with some of the date issues within the meeting object then, or have you got those issues ironed out? I can have a look tomorrow morning if needed.

**Comment by germainep** [comment]
It's was getting the date from the meeting to be set as the starting point for the time in availability I figured it out. Just haven't implemented it yet
