### ISSUE TITLE
TODO Signup View

### ISSUE THREAD

**Issue by aldraco** [FCCWebCrafts/timeCoordinatorApp#70]
As a User, I should ...
... be able to sign up using email/password
... signup using a social login

**Comment by germainep** [comment]
The way the passport authentication works if the user is not signed up and logs in with a social login it creates an account automatically with the social login info. In theory I would like to pop a modal after that happen for the user to create a local-login with name and password. I need to know if that would feel redundant.

**Comment by aldraco** [comment]
probably not necessary to ask the twitter users to put in a local option, but I do think some users would probably not want to use social profiles, so giving them a local option on the front end would be a nice feature. Not everyone uses social networking.

**Comment by germainep** [comment]
really all I'm trying to get at is a non-intrusive way to have the people who sign-in with social accounts to enter real names. This would allow the rolodex to query a list of real names. I had thought the name field was part of the local object in the model but its not

**Comment by aldraco** [comment]
We have a name property on the user object, but it's not populated until they enter a name. They can enter a name without a local login - maybe just have a modal pop up once they sign in the first time asking them to tell us thier name?

 I was just saying that it would be nice to allow people to choose to have a local login if they wanted and not have to use twitter/facebook/etc.

Also, we use 'username' and 'name' interchangeably, we should probably decide on which one we're going with. A name implies a real name, while a username implies something like sillyname039284.

**Comment by germainep** [comment]
That came from passport calling the local-login email username so I thought it was best to use name to avoid confusion

**Comment by aldraco** [comment]
passport doesn't call it anything except what you tell it to, in our config we tell it to use local-email instead of username (which is the default field it looks for) to log the user in. We can still have a username property on the user model if we wanted, it would be ignored by passport in lieu of the local-email. 

Previously you suggested that a real name was better than an arbitrary username, which I agree with. All I'm saying is that there are places in the code that say 'username' when they are updating the 'name' property on the User. We need to be more consistent and use one or the other.

However, if they are creating a local-login option, using an email instead of their name would be better. I have tried to use things like "A. Drake" as my name on sites, and having a period in the name or whatever will break it. Emails are more regulated. The name could be added after they have created their account.

**Comment by germainep** [comment]
I understand what parts of the code are using the username instead of name. I still believe that real names would be preferred. I think it would make it easy to find a person and more business ready. Is the inconsistency in the angular code, the html, or somewhere else.

**Comment by aldraco** [comment]
I completely agree that using real names is more professional. I don't want to be referred to as 'mrsducky876874' in a business setting ;)

There are just a few occasional instances in forms where the fields are referenced as 'username', on a few ng-models, and a few routes.

If we are deciding on 'name', I can try to change those as I find them.

**Comment by germainep** [comment]
The signup view is working and the current pull request will fix any other issues with login and sign up so I'm gonna close this issue
