### ISSUE TITLE
index routes are still rendering views

### ISSUE THREAD

**Issue by aldraco** [FCCWebCrafts/timeCoordinatorApp#72]
in routes/index.js

/signup renders 'signup.jade'
/login renders the login page

The FE/Ang layer should handle these views, and they should be stored in public, the root/views folder is for server side views - email templates, error pages, etc.

If this is leftover from before we added Angular then we should probably delete it.

**Comment by germainep** [comment]
Angular was added incrementally to avoid breaking authentication I'll work the routing around to the front end

**Comment by aldraco** [comment]
ok, makes sense.

**Comment by germainep** [comment]
The jade files for the front-end are being rendered on by the back-end

**Comment by aldraco** [comment]
Can you explain what you mean a little more? 

Usually Angular projects store views in the public/views folder, and the ui-router looks for the views there, so the views are rendered by Angular, not Express. This keeps the separation of concerns, since the view is not really related to the server at all, and the angular part is more self-contained.

**Comment by germainep** [comment]
since we started the project using jade files i continued to use jade files. The only way to render jade on the fly is to have it be rendered from express. The main reason this was done was to keep front-end if statements available

**Comment by germainep** [comment]
I was able to move the view files to the public/views folder and still use jade I will do a pull request with these changes

**Comment by germainep** [comment]
as far a the login/signup page its gonna take a bit of time to code those over. I'm wondering if it would be better to have a splash page and pop modals for the loginin and signup.

**Comment by aldraco** [comment]
sounds good to me (modals).

**Comment by aldraco** [comment]
Hey @germainep would it be helpful if I claim the login page project? I know you've been working on a lot of the Angular stuff, so please let me know if I can help you out at all.

**Comment by aldraco** [comment]
also I should probably close this issue, since you addressed it.

**Comment by germainep** [comment]
just an update i decided against modals at this time I did move the login page and profile pages to being routed through the front-end. that cause me to make separate profile and meeting pages so I utilized the nav bar that was on the page. I have to clean up the index.js  before I do a pull request so my next pull request maybe a little massive.

**Comment by aldraco** [comment]
that's fine - once we get to that point it will be easier to make smaller changes one at a time.

Thanks for taking on that part of the project, it's definitely not for the faint of heart.
