### ISSUE TITLE
edit profile controller redirects the user to another URL, should return a resource

### ISSUE THREAD

**Issue by aldraco** [FCCWebCrafts/timeCoordinatorApp#74]
controllers/users.js > editProfile

... to be REST compliant.

in other words, instead of redirecting the user on the server side, the front end should handle the redirects. The back end should just return resources or status codes.

**Comment by germainep** [comment]
This should be fixed in PR#78 angular now handles routing for all front-end and the server has a catch-all to prevent any unwanted redirection from the back-end

**Comment by aldraco** [comment]
awesome!
