### ISSUE TITLE
Suggestion: Unit Tests

### ISSUE THREAD

**Issue by aldraco** [FCCWebCrafts/timeCoordinatorApp#75]
If anyone is interested, I would love to have some test coverage on this app.

chai/mocha/karma would be great.

Thoughts?

**Comment by germainep** [comment]
currently working on this but it's slow going and I would love some help

**Comment by aldraco** [comment]
noted.

**Comment by germainep** [comment]
PR #78 adds some tools to do this but I haven't made any stern efforts to to test anything in particular
