### ISSUE TITLE
add other login options

### ISSUE THREAD

**Issue by aldraco** [FCCWebCrafts/timeCoordinatorApp#8]
Current strategies:
Twitter
Local
Google
Facebook

Suggestions are welcome for other methods. Sound off in the comments!

**Comment by germainep** [comment]
Should we add login with "GITHUB"??

**Comment by germainep** [comment]
Does anyone else have a suggestion that they would like to add before this closes. If there are no other suggestions by April 17 2015 EST this issue can be closed

**Comment by ThiagoFerreir4** [comment]
Login with yahoo, windows, and github login also sounds great.

**Comment by germainep** [comment]
I'll get to work on yahoo and windows soon then

**Comment by aldraco** [comment]
I'm going to close this for now as it was more of a sounding board, not an issue. Thanks guys.
