### ISSUE TITLE
documentation

### ISSUE THREAD

**Issue by aldraco** [FCCWebCrafts/timeCoordinatorApp#80]
It would be nice if we had some documentation on how the app is supposed to work, so other campers can easily contribute.

**Comment by aldraco** [comment]
I did a very basic version of this in the wiki, please check it out!

**Comment by germainep** [comment]
I love the wiki It explains exactly the then we need it to. sorry about the huge pull request they will be getting smaller after this last one

**Comment by ghost** [comment]
The Wiki is missing `npm install`. I followed it and ran into an error which reminded me you need to install the dependencies.
